import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import './globals.css'
import Header from '@/components/app-reusables/LandingPage/Header'
import NavBar from '@/components/app-reusables/LandingPage/NavBar'
import { ModalProvider } from './stores/context/modal'


const montserrat = Montserrat({ subsets: ['latin'], weight: "400" })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='background'>
      <body className={montserrat.className} style={{ backgroundImage: "#333651" }}>
        <Header />

        <section className='flex justify-between pt-[70px]'>
          <aside>
            <NavBar />
          </aside>
          <ModalProvider>
            <main className='h-full bg-backgroun bg-cover bg-no-repeat overflow-y-auto w-[calc(100%-140px)] ml-auto px-5'>
              {children}
            </main>
          </ModalProvider>

        </section>

      </body>
    </html>
  )
}
